title: Elky Review Log
description: 게임, IT 기기, 피규어 등 다양한 제품을 리뷰하는 블로그입니다.
logo: nes-squirtle
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

social:
  twitter: https://twitter.com/elky84
  facebook: https://facebook.com/elky1984
  github: https://github.com/elky84
  gmail: mailto:elky84@gmail.com
  youtube: https://youtube.com/channel/UC8ovI62bgJW8EpER0oyuPgQ
  # google: https://plus.google.com/username
  # medium: https://medium.com/@username
  twitch: https://twitch.com/elky84
  # reddit: https://www.reddit.com/user/username
  # whatsapp: tel:+5541999999999
  linkedin: https://www.linkedin.com/in/elky-96299bb1
disqus:
  shortname: elky

google_analytics: G-N76D2R0XPR
baseurl: /review

permalink: /:year/:title/
paginate: 10
author: 엘키